# Generated by Django 5.2.1 on 2025-07-27 22:17

import apps.account.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_user_username_alter_user_email_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', apps.account.managers.UserManager()),
            ],
        ),
    ]
