# Generated by Django 5.2.1 on 2025-06-21 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.basemodel')),
                ('name', models.CharField(max_length=80, verbose_name='Catalog name')),
                ('img', models.ImageField(upload_to='category_image/')),
            ],
            bases=('core.basemodel',),
        ),
    ]
