# Generated by Django 5.2.1 on 2025-07-02 08:22

import django.db.models.deletion
from django.db import migrations, models
from django.utils.text import slugify


def generate_slugs(apps, schema_editor):
    Catalog = apps.get_model('catalog', 'Catalog')
    for obj in Catalog.objects.all():
        obj.slug = slugify(obj.name)
        obj.save()

class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catalog',
            old_name='img',
            new_name='image_url',
        ),
        migrations.AddField(
            model_name='catalog',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.RunPython(generate_slugs),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.basemodel')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('image_url', models.ImageField(upload_to='subcategory_image/')),
                ('slug', models.SlugField(unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='catalog.catalog')),
            ],
            bases=('core.basemodel',),
        ),
    ]
