# Generated by Django 5.2.1 on 2025-07-25 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_material_remove_product_material_product_material'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='material',
            new_name='materials',
        ),
    ]
